version: '3.8'

services:
  db:
    image: postgres:15
    container_name: cs360_db
    restart: always
    environment:
      POSTGRES_USER: user_cs360
      POSTGRES_PASSWORD: password_cs360
      POSTGRES_DB: cs360_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: